### PR TITLE
Leaderboard: final touches

### PR DESCRIPTION
**Pull request by Paulinelali**
In this PR, I:
- [x] added styles of my choice except for the layout which is mandatory

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
Hi @Paulinelali, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linter checks. Please fix the errors and resubmit.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Paulinelali** [comment]
You are so funny @whiz25
Did you not see how previous branches were approved?

This webhint error is a general issue that almost everyone else facing, I personally called the Microverse staff attention to it and they said my project should not be rejected because of this, and I have been submitting projects for the last 2 or more weeks with this, why should you now reject my project because of this? As you can see, the layout branch, and hit the API branch were approved before I came to this final touches branch.

**Comment by zieeco** [comment]
@Paulinelali, I just want to point out a few things to you so you bear that in mind. I believe the previous reviewer @whiz25 didn't know there's an issue with the webhint which is currently on review to be fixed, and that's why he invalidated the PR. I think courtesy demands that you should be very professional in a remote setting like this. Your response doesn't sound professional. You should kindly improve on this. As for your project, it would be approved after being reviewed. I hope you learn more about how to communicate in remote settings to be more professional @Paulinelali.

**Review by zieeco — APPROVED** [review]
# status: APPROVED :green_circle: :100: 

Hi, @Paulinelali, 




Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
